# -*- coding: utf-8 -*-
"""bpe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kn04ly53SJonG08OsFoKdA1mOnIoKNQu

## This is the implemntation of the BPE (Byte Pair Encoding)
"""

# our training data set I copied the whole economic times
text = """The Economic Times
English Edition | 31 March, 2026, 11:35 AM IST | Today's ePaper
My WatchlistSubscribeSign In
Home
ETPrime
Markets
Market Data
Masterclass
IPO
News
Industry
SME
Politics
Wealth
MF
Tech
AI
Careers
Opinion
NRI
Panache
More
AIWeb StoriesITTech & InternetFundingStartupsTech BytesNewslettersBlogs & OpinionET Soonicorns SummitMore
AI News By
Industry
Featured
Healthcare
Media & Entertainment
Banking & Finance
Services
Ecommerce
Tech
Telecom
Energy
Auto
Manufacturing
Insights
Image for ET AI Hackathon 2026 enters final build sprint ahead of prototype submissions
ET AI Hackathon 2026 enters final build sprint ahead of prototype submissions
With just days left until submissions close on March 29, the ET AI Hackathon 2026 enters its most decisive stretch. Shortlisted teams are now deep in development, refining prototypes under real constraints. The focus has shifted entirely to execution, where clarity, functionality, and real-world relevance will determine which ideas stand out.

ET AI Hackathon 2026 enters prototype stage, where ideas meet their hardest test
Image for ET AI Hackathon 2026 enters prototype stage, where ideas meet their hardest test
ET GenAI Hackathon 2026: Phase 1 results out, prototype stage begins
Image for ET GenAI Hackathon 2026: Phase 1 results out, prototype stage begins
Now searching: Women in AI
Image for Now searching: Women in AI
The Gen AI Hackathon that has India's tech community talking
Image for The Gen AI Hackathon that has India's tech community talking
Sarvam open-sources 30B, 105B reasoning models; here’s what it means
Image for Sarvam open-sources 30B, 105B reasoning models; here’s what it means
From scale to structure: The ET Gen AI Hackathon and India’s next phase of AI
Image for From scale to structure: The ET Gen AI Hackathon and India’s next phase of AI
News that matters to you directly in your inbox.
AI-powered tool to create the auto-generated newsletter you want.

Generate AI Newsletter
Explore Courses
arrowIcon
IIT Programs
cardImage
2026’s AI Power Plays: Certifications That Mint Tomorrow’s Leaders
Know More
arrowIcon
cardImage
The AI Certs That’ll Make 2026 Your Breakout Year
Know More
arrowIcon
cardImage
AI Programmes That'll Make Recruiters’ Bots Swoon in 2026
Know More
arrowIcon
cardImage
The AI Certs That’ll Make 2026 Your Breakout Year
Know More
arrowIcon



Tools - Updates, Training, Compliance
Voice to Text Generator
​Text to Audio Generator​
​AI Image Editor​
​AI Presentation​
​AI Content Writing​
​AI Avtar Generator​
​AI Video Generator​
​AI Image Generator​
Image For Wispr Flow AI
Wispr Flow AI
Wispr Flow AI is a tool that turns your spoken words into clear tasks and notes. It helps you work faster by quickly organizing what you say into easy-to-use actions.

Image For Otter AI
Otter AI
Otter AI is a tool that listens to your meetings and turns them into clear notes. It helps you save time by automatically capturing key points, tasks, and summaries.

Image For Speech Notes AI
Speech Notes AI
Speechnotes AI is a tool that turns your spoken words into written text instantly. It helps you write faster by letting you speak instead of typing.

Image For Descript AI
Descript AI
Descript AI is a tool that turns audio into clean written text automatically. It helps you edit recordings easily by letting you edit the text like a document.

Image For Fireflies AI
Fireflies AI
Fireflies AI is a tool that records your meetings and turns them into easy-to-read notes. It helps you save time by capturing key points, tasks, and summaries automatically.

Image For Sonix AI
Sonix AI
Sonix AI is a tool that quickly turns audio and video into written text. It helps you stay organized by giving you accurate transcripts you can search, edit, and share easily.

Image For RecCloud AI
RecCloud AI
RecCloud AI is a tool that turns your voice or audio into clear written text. It helps you work faster by quickly creating transcripts you can edit and share.

Image For Quillbot AI
Quillbot AI
QuillBot AI is a tool that turns your spoken words into clear written text. It helps you write faster by accurately capturing what you say and putting it into easy-to-edit sentences.

Image For Murf AI
Murf AI
Murf AI is a tool that can turn your voice into written text quickly. It helps you create scripts or notes easily by converting what you say into clean, editable text.

News By
Job Types
Tech
Operations
Marketing
HR
Image for Meta hires four more OpenAI researchers: Report
Meta hires four more OpenAI researchers: Report
The researchers, Shengjia Zhao, Jiahui Yu, Shuchao Bi and Hongyu Ren have each agreed to join, the report said, citing a person familiar with their hiring.

OpenAI's ChatGPT down; users report issues in loading prompts
Image for OpenAI's ChatGPT down; users report issues in loading prompts
Apple to open up underlying AI technology to developers
Image for Apple to open up underlying AI technology to developers
US-UAE multi-billion dollar AI data campus deal far from finalised, sources say
Image for US-UAE multi-billion dollar AI data campus deal far from finalised, sources say
Are you saying 'thanks', 'please' to ChatGPT? It's costing OpenAI millions
Image for Are you saying 'thanks', 'please' to ChatGPT? It's costing OpenAI millions
AI Live Stream
View All
India AI Impact Summit 2026Play Icon
India AI Impact Summit 2026
Streamed 1 month ago

Watch Now
India AI Impact Summit 2026Play Icon
India AI Impact Summit 2026
Streamed 1 month ago

Watch Now
India AI Impact Summit 2026Play Icon
India AI Impact Summit 2026
Streamed 1 month ago

Watch Now
Videos
AI Videos - YouTube
The Founder Playbook for Production Ready Voice AIPlay Icon
The Founder Playbook for Production Ready Voice AI
The Founder Playbook for Production Ready Voice AI
The Founder Playbook for Production Ready Voice AI

90 Seconds from Goal to Global: How AI Is Rewriting Sports Broadcasting
90 Seconds from Goal to Global: How AI Is Rewriting Sports Broadcasting

Your Sales Team Is Missing 70% of Buyer Signals — This AI Doesn’t
Your Sales Team Is Missing 70% of Buyer Signals — This AI Doesn’t

Inside the AI Startup Cutting Clinical Notes from Minutes to Seconds
Inside the AI Startup Cutting Clinical Notes from Minutes to Seconds

How AI Is Reshaping the Fashion Design Supply Chain | ET AI Podcast
How AI Is Reshaping the Fashion Design Supply Chain | ET AI Podcast

How AI Is Changing Fashion Discovery | Esha Tiwary, Founder and CEO of Furrl | ET AI Podcast
How AI Is Changing Fashion Discovery | Esha Tiwary, Founder and CEO of Furrl | ET AI Podcast

Building India’s AI Agents for Voice, Text and Video with Gnani.ai
Building India’s AI Agents for Voice, Text and Video with Gnani.ai

ET AI Podcast with Amitabh Nag: How Language AI Can Bridge India’s Digital & Literacy Divide
ET AI Podcast with Amitabh Nag: How Language AI Can Bridge India’s Digital & Literacy Divide

What is generative AI and how does it work? – The Turing Lectures with Mirella Lapata
What is generative AI and how does it work? – The Turing Lectures with Mirella Lapata

The AI Revolution Is Underhyped | Eric Schmidt | TED
The AI Revolution Is Underhyped | Eric Schmidt | TED

Short Videos
Image For Alternatives to 11Labs is Powerful | But These FREE Voice AI Tools Might Surprise Youplay icon
Image For ET AI-Vox Popplay icon
Image For global ai race - et aiplay icon
Image For How to Identify the Right AI Toolplay icon
Image For AI Crisisplay icon
Image For Beyond Marksplay icon
Image For How AI is Transforming Cybersecurity in 2025play icon
Image For Ever feel like Spotify reads your mind?play icon
Image For ET AI codingplay icon
Image For Deepfakes: Cool Tech or Dangerous Trick?play icon
Image For How Netflix hooks you with AIplay icon
Image For How AI is shaping future of Educationplay icon
Image For Meet Nova Act: Amazon's AI Assistant for Your Daily Tasksplay icon
Image For AI vs AGI – What’s the Difference?play icon



Weekly Capsule
Image for AI Weekly Capsule: Key Global Movement: A day-by-day breakdown of the most defining AI events from 21-28 Nov.
Download
AI Weekly Capsule: Key Global Movement: A day-by-day breakdown of the most defining AI events from 21-28 Nov.
Weekly AI capsule 24th April: South Korea Flags DeepSeek Data Misuse
ET AI Weekly Capsule 17th April: OpenAI's Big Bets,Deepfake Dangers, and the Global AI Power Race
What You will learn With Us in 3 minutes
Daily, expert-curated 3-minute AI insights: concise breakthroughs, trends, applications, and practical tips empowering innovators, leaders, entrepreneurs, researchers, businesses, and enthusiasts.

Image For AI In 3 Mins
Download PDF
Image For AI In 3 Mins: Prompt of the Week
Download PDF
Image For AI In 3 Mins: Man falls ill after following ChatGPT's health advice
Download PDF
Image For AI in 3 Mins:
Download PDF
Image For AI In 3 Mins : GPT-5 update
Download PDF
Image for ET Lazy Load Image
Daily Newsletter
Stay ahead of AI's daily evolution – subscribe for exclusive insights!

Enter Email address
Subscribe
Image for AI Linkedin
Image For AI About
About Us
ET AI brings you the latest in artificial intelligence — from breakthroughs in machine learning to real-world applications across industries. Explore how AI is transforming business, innovation, and decision-making at the speed of thought.

1M+
SUBSCRIBERS
6M+
IMPRESSIONS
7M+
READERS
Contact Us
Sponsor an Event
Increase your brand visibility and thought leadership in Industry

Host an Exclusive Event
Host events with ET expertise and engage your target audience

Exhibit Products & Services
Showcase your product to industry influencers and CXOs

Get In Touch
The Economic TimesEnter your email address:
Search News, Stock Quotes & NAV
Popular Categories

More
AIWeb StoriesITTech & InternetFundingStartupsTech BytesNewslettersBlogs & OpinionET Soonicorns SummitET Most Promising StartupTech and Gadgets
Hot on Web

More
Horoscope Today, 31 March, 202622k Gold Rate TodayIRB Infrastructure share priceHoroscope Tomorrow, 31 March 2026Sensex Today Live UpdatesGold Silver Rate Today Live UpdatesSensex Today Live UpdatesEid Mubarak WishesHRA exemption in Income Tax Rules 2026HDFC Bank Share Price8th Pay Commission Salary HikeOscars 2026 Best Actor WinnerOscars 2026 full winners list live updatesElection dates 2026Kerala Election Date 2026Puducherry election date 2026Assam Election Date 2026Formula 1
In Case you missed it

More
Narayana MurthyXiaomi Mi Mix 2Reliance JioJio PhoneJio PhoneGreat Indian SaleGold rate TodayiPhone 8 Launch IndiaGoogle Payments AppInfosysGoogle Tez AppJio Phone BookingInfosysNarayana MurthyVishal SikkaCognizant
Top Searched Companies

More
IRFC share priceSuzlon share priceIREDA share priceTATA Motors share priceYes bank share priceHDFC Bank share priceNHPC share priceRVNL share priceSBI share priceTata power share priceTata steel share priceAdani power share pricePaytm share pricePNB share priceZomato share priceBEL share priceBHEL share priceInfosys share priceIRCTC share priceITC share priceJIO finance share priceLIC share priceReliance share priceHAL share priceJP Power share priceNBCC share priceTCS share priceVedanta share priceWipro share priceIOC share priceIrcon share priceSAIL share priceSJVN share priceGAIL share priceHUDCO share priceREC share priceReliance Power share priceTata Technologies share priceVodafone idea share priceAdani Enterprises share priceAdani Green share priceAdani Port share priceAshok Leyland share priceBank of Baroda share priceBSE share priceCanara Bank share priceCDSL share priceCoal India share priceHFCL share priceIDFC First Bank share price
Other useful Links

More
About UsArchiveTerms of Use & Grievance RedressalEconomic Times ePaperGrow FastTimes Health+Privacy policyCreate Your Own AdAdvertise with UsSubscribe to ET PrimeContact UsRSSDNPA Code of EthicsLongwalks AppCareersTimesEvents
Top Calculators

More
Standard Deviation CalculatorIncome Tax CalculatorAge CalculatorSIP CalculatorTime CalculatorBMI CalculatorGPA CalculatorStatistics CalculatorFraction CalculatorDiabetes Risk CalculatorDate CalculatorLog Calculator
Top Commodities

More
Aluminium RateGold Rate In KolkataZinc RateGold Rate In ChennaiCrudeoil RateSilver RateNickel RateGold RateGold Rate In DelhiGold Rate In HyderabadMenthaoil RateKapas RateCopper RateCotton RateGold Rate In MumbaiGold Rate In Bangalore
Top Prime Articles

More
After Adani Stocks Hindenburg May Have Crashed Into Indias Green Hydrogen Mission TooFalling Off The Momentum Why Retail Investors Are Losing Money After Witnessing A Long RallyNo 5g Service Lack Of Fresh Funds Could Further Hurt Vodafone Idea Even As Airtel Jio Leap AheadMens Underwear Sales Are Falling Should Indian Economy Prepare For A Below The Belt JoltAdani Group Stocks Will Averaging Out Work For Retail InvestorsNippon India Fund DirectWe Want To Solve The Wazirx Binance Issue Once And For All Nischal ShettyReliance Jiocinema Is Streaming Ipl 2023 For Free Will This Now Disrupt The Ott BusinessIs Nifty Next 50 A Good Bet Only If You Are A Super Long Term InvestorIndian It Companies Rode The Cloud Wave As Hyperscalers Growth Tapers How Will It Impact Them
Top Story Listing

More
Tcs LayoffsEarthquake In DelhiEpfo PensionNifty CrashEarthquake TodayStock Market CrashLicEpfoSgx NiftyDangal
Top Definitions

More
BusinessFiscal DeficitMarketsMapsko Builders Private LimitedFpoProductRepo RateAccountingMarketing MixCurrency Symbol
Top Slideshow

More
How Rajendra Badwe Is Making Cancer Treatment Affordable By Repurposing Easily Available DrugsRaw VegetablesStock IdeasAxis BankIcici Bank
Top Market Pages

More
Fully Drawn Advance
Latest News

Yield tops 7%, banks stare at bigger MTM losses
F&O trading to get costlier from April 1 as curbs on speculation kick in
Jaden Ivey waived by Chicago Bulls after controversial Instagram comments - what did he say about LGBTQ, abortion and 50 Cent?
Bank FD tally in Q3 falls to 2-year low, total deposit base growth also slips
Kuwaiti loaded oil tanker ablaze in Dubai Port after Iranian attack
Netanyahu says Iran ops 'beyond halfway point', focus now on enriched uranium stockpile
Bank stocks fall as Street factors in lower profits
Brokerages turn bullish on HDFC Bank after sharp 26% correction
RBI defers capital market exposure norms to July 1
RBI allows SFBs to lend to MIs, sets fresh LTV ratio norms
Social media platform Fanon raises $1 million in round led by Kalaari, Gruhas
ETtech Explainer: What Emergent’s ARR reveals about AI’s numbers game
Cyber pirates at large, India readies moats
Quick commerce expands beyond groceries with VC funding, but scale questions persist
Early-stage funding value ticks up 46%, but numbers decrease
follow us on

Download ET App:

subscribe to our newsletter
Copyright © 2026 Bennett, Coleman & Co. Ltd. All rights reserved. For reprint rights: Times Syndication Service

"""


print(len(text))

tokens = list(text.encode("utf-8")) # raw bytes of text --> int
print(len(tokens))

def pairing(tokens): # pair baisis of frequency
    pairs = {}
    for pair in zip(tokens,tokens[1:]):
        pairs[pair] = pairs.get(pair,0)+1
    return pairs

pairs = pairing(tokens)
top_pair = max(pairs,key=pairs.get)

def merge(old_tokens,top_pair,idx):
    new_tokens = []
    i=0
    while i<len(old_tokens):
        if i<len(old_tokens)-1 and top_pair[0] ==  old_tokens[i] and top_pair[1] == old_tokens[i+1]:
            new_tokens.append(idx)
            i+=2
        else:
            new_tokens.append(old_tokens[i])
            i+=1
    return new_tokens

new_tokens = merge(tokens,top_pair,256)
len(new_tokens)

merges = {}

merges[top_pair] = 256
vocab_size  = 275

num_merges = vocab_size-256
org_tokens = tokens

for i in range(num_merges):
    pair = pairing(new_tokens)
    top_pair = max(pair,key=pair.get)
    idx = 257+i
    new_tokens = merge(new_tokens,top_pair,idx)
    merges[top_pair] = idx



vocab = {idx:bytes([idx]) for idx in range(256)}

for (p0,p1),v in merges.items():
    vocab[v] = vocab[p0] + vocab[p1]

def decode(ids): # ids to text
    tokens = b"".join(vocab[idx] for idx in ids)
    text = tokens.decode('utf-8',errors='replace')
    return text

decode([100,101,102,103])

def encode(text):
    tokens = list(text.encode("utf-8"))

    while 2<=len(tokens):
        pairs = pairing(tokens)
        bottom_pair = min(pairs,key = lambda p: pairs.get(p,float("inf")))

        if bottom_pair not in merges:
            break

        idx = merges[bottom_pair]
        tokens = merge(tokens,bottom_pair,idx)
    return tokens




























